<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cart;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new ClassMetadata(Cart::class) : $metadata);
    }

    /**
     * @param Cart $cart
     * @return bool
     * @throws ORMException
     */
    public function insert(Cart $cart)
    {
        try {
            $this->_em->persist($cart);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Cart $cart
     * @return bool
     * @throws ORMException
     */
    public function update(Cart $cart)
    {
        try {
            $this->_em->merge($cart);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }

    /**
     * @param Cart $cart
     * @return bool
     * @throws ORMException
     */
    public function remove(Cart $cart)
    {
        try {
            $this->_em->remove($cart);
            $this->_em->flush();
            return true;
        } catch (OptimisticLockException $e) {
            return false;
        }
    }
}
