<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Jewellery;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\ORMException;

/**
 * JewelleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JewelleryRepository extends EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new ClassMetadata(Jewellery::class) : $metadata);
    }

    /**
     * @param Jewellery $jewellery
     * @return bool
     */
    public function insert(Jewellery $jewellery)
    {
        try {
            $this->_em->persist($jewellery);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    /**
     * @param Jewellery $jewellery
     * @return bool
     */
    public function update(Jewellery $jewellery)
    {
        try {
            $this->_em->merge($jewellery);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    /**
     * @param Jewellery $jewellery
     * @return bool
     */
    public function remove(Jewellery $jewellery)
    {
        try {
            $this->_em->remove($jewellery);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }
}
