<?php

namespace AppBundle\Repository;

use AppBundle\Entity\ShipmentItems;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use Doctrine\ORM\ORMException;

/**
 * ShipmentItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShipmentItemsRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em,
                                ClassMetadata $metadata = null)
    {
        parent::__construct($em,
            $metadata == null ?
                new ClassMetadata(ShipmentItems::class) : $metadata);
    }

    /**
     * @param ShipmentItems $item
     * @return bool
     */
    public function insert(ShipmentItems $item)
    {
        try {
            $this->_em->persist($item);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    /**
     * @param ShipmentItems $item
     * @return bool
     */
    public function update(ShipmentItems $item)
    {
        try {
            $this->_em->merge($item);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }

    /**
     * @param ShipmentItems $item
     * @return bool
     */
    public function remove(ShipmentItems $item)
    {
        try {
            $this->_em->remove($item);
            $this->_em->flush();
            return true;
        } catch (ORMException $e) {
            return false;
        }
    }
}
